name: app_tutorial
description: Package for creating tutorials for your app to explain the features of the app in a seamless ways to you users.
version: 0.2.3
homepage: https://github.com/aikenahac/app-tutorial

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_staggered_grid_view: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: